version: "3.0"
services:
  cvs-export:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "CSV Export"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      PROFILE_IDS: ''
      MATCHED_URL: ''
    ports:
      - 80:80
