version: "3.0"
services:
  cvs-export:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "CSV Export"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      FILENAME: "export"
      DIR_PATH: "/data"
      DELIMITER: "comma"
      SPLIT_TYPE: "size"
      SPLIT_SIZE: "1024"
      INCLUDE_TIMESTAMP: "true"
    ports:
      - 80:80
